### ISSUE TITLE
event.preventDefault does not work inside of forms.

### ISSUE THREAD

**Issue by chiwoojo** [snowcoders/react-checkbox#25]
Because input and button both fire events in this component, there is no way to prevent default event from the parent component using this component. Can you fix? Thanks.

**Comment by k2snowman69** [comment]
I think an example would help here... I'm curious as to when this is useful outside of form submit (which in that case you should be preventing the form from submitting). I'll still look into preventing the button's default behavior (which makes sense) just an example would help here to get more context and to write unit tests.

**Comment by k2snowman69** [comment]
I've added a prevent default to the button... the checkbox click will still go through the full cycle. Hopefully that fixes your problem?

Version 0.2.0.

**Comment by chiwoojo** [comment]
Thanks! I will give it a shot.

**Comment by k2snowman69** [comment]
Just curious if this was resolved for you... let me know so I can close it out :-)

**Comment by chiwoojo** [comment]
This was resolved. Thanks!
